// Type definitions for core-helper-packages v2.0.0
// Works with TypeScript, Angular, React, Vue
// Author: Jeel Patel

export type AnyValue = any;
export type Callback<T = any> = (value: T, index?: number) => any;
export type Predicate<T = any> = (value: T, index?: number) => boolean;
export type KeyFn<T = any> = (value: T) => string | number;

// ─── TYPE UTILITIES ───────────────────────────────────────────────────────────
export function isString(value: any): value is string;
export function isNumber(value: any): value is number;
export function isBoolean(value: any): value is boolean;
export function isObject(value: any): value is object;
export function isFunction(value: any): value is Function;
export function isArray(value: any): value is any[];
export function isNull(value: any): value is null;
export function isUndefined(value: any): value is undefined;
export function isNullOrUndefined(value: any): value is null | undefined;
export function isInteger(value: any): value is number;
export function isFloat(value: any): value is number;
export function isNaN(value: any): boolean;
export function isFinite(value: any): boolean;
export function isDate(value: any): value is Date;
export function isRegExp(value: any): value is RegExp;
export function isSymbol(value: any): value is symbol;
export function isBigInt(value: any): value is bigint;
export function isMap(value: any): value is Map<any, any>;
export function isSet(value: any): value is Set<any>;
export function isWeakMap(value: any): value is WeakMap<any, any>;
export function isWeakSet(value: any): value is WeakSet<any>;
export function isPromise(value: any): value is Promise<any>;
export function isError(value: any): value is Error;
export function isArrayBuffer(value: any): value is ArrayBuffer;
export function isTypedArray(value: any): boolean;
export function isGeneratorFunction(value: any): boolean;
export function isPlainObject(value: any): value is Record<string, any>;
export function isIterable(value: any): boolean;
export function isAsyncFunction(value: any): boolean;
export function isEmpty(value: any): boolean;
export function isTruthy(value: any): boolean;
export function isFalsy(value: any): boolean;
export function isEqual(a: any, b: any): boolean;
export function isDeepEqual(a: any, b: any): boolean;
export function isPrimitive(value: any): boolean;
export function isObjectLike(value: any): boolean;
export function isNonEmptyString(value: any): value is string;
export function isPositive(value: any): boolean;
export function isNegative(value: any): boolean;
export function isZero(value: any): boolean;
export function isSafeInteger(value: any): boolean;
export function isEven(value: any): boolean;
export function isOdd(value: any): boolean;
export function typeOf(value: any): string;

// ─── ARRAY UTILITIES ──────────────────────────────────────────────────────────
export function isArrayEmpty(arr: any[]): boolean;
export function getArrayLength(arr: any[]): number;
export function firstElement<T>(arr: T[]): T | undefined;
export function lastElement<T>(arr: T[]): T | undefined;
export function nthElement<T>(arr: T[], n: number): T | undefined;
export function pushElement<T>(arr: T[], element: T): T[];
export function popElement<T>(arr: T[]): T[];
export function unshiftElement<T>(arr: T[], element: T): T[];
export function shiftElement<T>(arr: T[]): T[];
export function indexOfElement<T>(arr: T[], element: T): number;
export function includesElement<T>(arr: T[], element: T): boolean;
export function findElement<T>(arr: T[], predicate: Predicate<T>): T | undefined;
export function findIndexElement<T>(arr: T[], predicate: Predicate<T>): number;
export function beforeArray<T>(arr: T[], index: number): T[];
export function afterArray<T>(arr: T[], index: number): T[];
export function sumArray(arr: number[]): number;
export function averageArray(arr: number[]): number;
export function maxArray(arr: number[]): number;
export function minArray(arr: number[]): number;
export function median(arr: number[]): number;
export function mode(arr: any[]): any[];
export function variance(arr: number[]): number;
export function standardDeviation(arr: number[]): number;
export function percentile(arr: number[], p: number): number;
export function cumSum(arr: number[]): number[];
export function cumProduct(arr: number[]): number[];
export function movingAverage(arr: number[], window: number): number[];
export function mapArray<T, U>(arr: T[], cb: (item: T, index: number, arr: T[]) => U): U[];
export function filterArray<T>(arr: T[], pred: Predicate<T>): T[];
export function reduceArray<T, U>(arr: T[], cb: (acc: U, val: T, i: number) => U, init: U): U;
export function flatArray(arr: any[]): any[];
export function flatOnce(arr: any[]): any[];
export function flatDepth(arr: any[], depth: number): any[];
export function flatMapArray<T, U>(arr: T[], cb: (item: T) => U[]): U[];
export function uniqueArray<T>(arr: T[]): T[];
export function uniqueBy<T>(arr: T[], keyFn: KeyFn<T>): T[];
export function sortArray<T>(arr: T[], compareFn?: (a: T, b: T) => number): T[];
export function sortBy<T>(arr: T[], key: keyof T, order?: 'asc' | 'desc'): T[];
export function reverseArray<T>(arr: T[]): T[];
export function compactArray(arr: any[]): any[];
export function compactNullish<T>(arr: (T | null | undefined)[]): T[];
export function chunkArray<T>(arr: T[], size: number): T[][];
export function dropArray<T>(arr: T[], n?: number): T[];
export function dropRight<T>(arr: T[], n?: number): T[];
export function takeArray<T>(arr: T[], n?: number): T[];
export function takeRight<T>(arr: T[], n?: number): T[];
export function dropWhile<T>(arr: T[], pred: Predicate<T>): T[];
export function takeWhile<T>(arr: T[], pred: Predicate<T>): T[];
export function rotate<T>(arr: T[], n?: number): T[];
export function fillArray<T>(arr: T[], value: T, start?: number, end?: number): T[];
export function range(start: number, end: number, step?: number): number[];
export function rangeOf(n: number): number[];
export function intersectArray<T>(arr1: T[], arr2: T[]): T[];
export function unionArray<T>(arr1: T[], arr2: T[]): T[];
export function differenceArray<T>(arr1: T[], arr2: T[]): T[];
export function symmetricDifference<T>(arr1: T[], arr2: T[]): T[];
export function isSubset<T>(arr1: T[], arr2: T[]): boolean;
export function arrayEquals<T>(arr1: T[], arr2: T[]): boolean;
export function groupBy<T>(arr: T[], keyFn: KeyFn<T>): Record<string, T[]>;
export function partition<T>(arr: T[], pred: Predicate<T>): [T[], T[]];
export function countBy<T>(arr: T[], keyFn: KeyFn<T>): Record<string, number>;
export function indexBy<T>(arr: T[], keyFn: KeyFn<T>): Record<string, T>;
export function pluck<T, K extends keyof T>(arr: T[], key: K): T[K][];
export function tally(arr: any[]): Record<string, number>;
export function frequencies(arr: any[]): Record<string, number>;
export function zipArray(...arrays: any[][]): any[][];
export function unzipArray(arr: any[][]): any[][];
export function zipWith<T>(fn: (...args: any[]) => T, ...arrays: any[][]): T[];
export function zipObject<T>(keys: string[], values: T[]): Record<string, T>;
export function fromPairs(pairs: [string, any][]): Record<string, any>;
export function toPairs(obj: Record<string, any>): [string, any][];
export function combinations<T>(arr: T[], r: number): T[][];
export function permutations<T>(arr: T[]): T[][];
export function powerSet<T>(arr: T[]): T[][];
export function cartesianProduct<A, B>(arr1: A[], arr2: B[]): [A, B][];
export function sample<T>(arr: T[]): T;
export function sampleSize<T>(arr: T[], n: number): T[];
export function shuffle<T>(arr: T[]): T[];
export function insertAt<T>(arr: T[], index: number, element: T): T[];
export function removeAt<T>(arr: T[], index: number): T[];
export function swapElements<T>(arr: T[], i: number, j: number): T[];
export function without<T>(arr: T[], ...values: T[]): T[];
export function updateAt<T>(arr: T[], index: number, value: T): T[];
export function toMatrix<T>(arr: T[], cols: number): T[][];
export function matrixTranspose<T>(matrix: T[][]): T[][];
export function arrayToTree<T>(arr: T[], options?: { id?: string; parentId?: string; children?: string }): T[];

// ─── STRING UTILITIES ─────────────────────────────────────────────────────────
export function capitalize(str: string): string;
export function capitalizeWords(str: string): string;
export function camelCase(str: string): string;
export function snakeCase(str: string): string;
export function kebabCase(str: string): string;
export function pascalCase(str: string): string;
export function titleCase(str: string): string;
export function constantCase(str: string): string;
export function dotCase(str: string): string;
export function pathCase(str: string): string;
export function swapCase(str: string): string;
export function trim(str: string): string;
export function trimStart(str: string): string;
export function trimEnd(str: string): string;
export function padStart(str: string, len: number, char?: string): string;
export function padEnd(str: string, len: number, char?: string): string;
export function padBoth(str: string, len: number, char?: string): string;
export function repeat(str: string, n: number): string;
export function reverse(str: string): string;
export function reverseWords(str: string): string;
export function isPalindrome(str: string): boolean;
export function isAnagram(a: string, b: string): boolean;
export function startsWith(str: string, prefix: string): boolean;
export function endsWith(str: string, suffix: string): boolean;
export function includesStr(str: string, sub: string): boolean;
export function isBlank(str: string): boolean;
export function countOccurrences(str: string, sub: string): number;
export function wordCount(str: string): number;
export function charCount(str: string, includeSpaces?: boolean): number;
export function lineCount(str: string): number;
export function nthWord(str: string, n: number): string | undefined;
export function extractEmails(str: string): string[];
export function extractUrls(str: string): string[];
export function extractHashtags(str: string): string[];
export function extractMentions(str: string): string[];
export function extractNumbers(str: string): number[];
export function replaceAll(str: string, search: string, replace: string): string;
export function stripHtml(str: string): string;
export function escapeHtml(str: string): string;
export function unescapeHtml(str: string): string;
export function escapeRegex(str: string): string;
export function slugify(str: string): string;
export function deslugify(str: string): string;
export function truncate(str: string, maxLen: number, suffix?: string): string;
export function truncateWords(str: string, maxWords: number, suffix?: string): string;
export function wrapText(str: string, maxLen: number): string;
export function indent(str: string, spaces?: number): string;
export function dedent(str: string): string;
export function maskString(str: string, visibleStart?: number, visibleEnd?: number, char?: string): string;
export function maskEmail(email: string): string;
export function maskPhone(phone: string): string;
export function maskCreditCard(num: string): string;
export function base64Encode(str: string): string;
export function base64Decode(str: string): string;
export function hexEncode(str: string): string;
export function hexDecode(hex: string): string;
export function rot13(str: string): string;
export function caesarCipher(str: string, shift: number): string;
export function levenshteinDistance(a: string, b: string): number;
export function jaroWinkler(s1: string, s2: string): number;
export function longestCommonPrefix(a: string, b: string): string;
export function longestCommonSubstring(a: string, b: string): string;
export function getInitials(str: string): string;
export function abbreviate(str: string, n?: number): string;
export function humanize(str: string): string;
export function ordinalize(n: number | string): string;
export function pluralize(word: string, count?: number): string;
export function singularize(word: string): string;
export function interpolate(template: string, data: Record<string, any>): string;
export function randomString(len?: number, chars?: string): string;
export function randomAlpha(len?: number): string;
export function randomHex(len?: number): string;
export function randomAlphaNumeric(len?: number): string;
export function splitByLength(str: string, n: number): string[];
export function byteLength(str: string): number;

// ─── NUMBER UTILITIES ─────────────────────────────────────────────────────────
export function clamp(num: number, min: number, max: number): number;
export function inRange(num: number, min: number, max: number): boolean;
export function normalize(num: number, min: number, max: number): number;
export function mapRange(num: number, inMin: number, inMax: number, outMin: number, outMax: number): number;
export function random(min?: number, max?: number): number;
export function randomInt(min: number, max: number): number;
export function randomFloat(min: number, max: number, decimals?: number): number;
export function roundTo(num: number, decimals?: number): number;
export function ceilTo(num: number, decimals?: number): number;
export function floorTo(num: number, decimals?: number): number;
export function abs(num: number): number;
export function sign(num: number): number;
export function trunc(num: number): number;
export function sqrt(num: number): number;
export function cbrt(num: number): number;
export function pow(a: number, b: number): number;
export function log(num: number): number;
export function log2(num: number): number;
export function log10(num: number): number;
export function gcd(a: number, b: number): number;
export function lcm(a: number, b: number): number;
export function factorial(n: number): number;
export function fibonacci(n: number): number;
export function fibonacciSequence(n: number): number[];
export function isPrime(n: number): boolean;
export function primesUpTo(n: number): number[];
export function nextPrime(n: number): number;
export function prevPrime(n: number): number | null;
export function isPerfect(n: number): boolean;
export function isAbundant(n: number): boolean;
export function digitSum(n: number): number;
export function digitProduct(n: number): number;
export function reverseNumber(n: number): number;
export function isNumericPalindrome(n: number): boolean;
export function toBinary(n: number): string;
export function toOctal(n: number): string;
export function toHex(n: number): string;
export function fromBinary(bin: string): number;
export function fromOctal(oct: string): number;
export function fromHex(hex: string): number;
export function convertBase(numStr: string, fromBase: number, toBase: number): string;
export function formatNumber(num: number, locale?: string): string;
export function formatCurrency(num: number, currency?: string, locale?: string): string;
export function formatPercent(num: number, decimals?: number, locale?: string): string;
export function formatBytes(bytes: number, decimals?: number): string;
export function bytesToKB(b: number): number;
export function bytesToMB(b: number): number;
export function bytesToGB(b: number): number;
export function kbToBytes(kb: number): number;
export function mbToBytes(mb: number): number;
export function gbToBytes(gb: number): number;
export function degreesToRadians(deg: number): number;
export function radiansToDegrees(rad: number): number;
export function celsiusToFahrenheit(c: number): number;
export function fahrenheitToCelsius(f: number): number;
export function celsiusToKelvin(c: number): number;
export function kelvinToCelsius(k: number): number;
export function fahrenheitToKelvin(f: number): number;
export function kelvinToFahrenheit(k: number): number;
export function kmToMiles(km: number): number;
export function milesToKm(miles: number): number;
export function kgToLbs(kg: number): number;
export function lbsToKg(lbs: number): number;
export function metersToFeet(m: number): number;
export function feetToMeters(ft: number): number;
export function litersToGallons(l: number): number;
export function gallonsToLiters(gal: number): number;
export function msToKmh(ms: number): number;
export function kmhToMs(kmh: number): number;
export function percentage(part: number, total: number): number;
export function percentageOf(p: number, total: number): number;
export function percentageChange(oldVal: number, newVal: number): number;

// ─── OBJECT UTILITIES ─────────────────────────────────────────────────────────
export function keys(obj: Record<string, any>): string[];
export function values<T>(obj: Record<string, T>): T[];
export function entries<T>(obj: Record<string, T>): [string, T][];
export function fromEntries<T>(pairs: Iterable<[string, T]>): Record<string, T>;
export function size(obj: Record<string, any>): number;
export function isEmptyObject(obj: Record<string, any>): boolean;
export function pick<T extends object, K extends keyof T>(obj: T, keyList: K[]): Pick<T, K>;
export function omit<T extends object, K extends keyof T>(obj: T, keyList: K[]): Omit<T, K>;
export function pickBy<T extends object>(obj: T, predFn: (value: any, key: string) => boolean): Partial<T>;
export function omitBy<T extends object>(obj: T, predFn: (value: any, key: string) => boolean): Partial<T>;
export function get(obj: any, path: string, defaultValue?: any): any;
export function set(obj: any, path: string, value: any): any;
export function has(obj: any, path: string): boolean;
export function unset(obj: any, path: string): any;
export function assign(...objs: object[]): object;
export function mergeDeep(...objs: object[]): object;
export function clone<T extends object>(obj: T): T;
export function cloneDeep<T>(obj: T): T;
export function defaults(obj: object, ...defaultObjs: object[]): object;
export function mapValues<T, U>(obj: Record<string, T>, fn: (value: T, key: string) => U): Record<string, U>;
export function mapKeys<T>(obj: Record<string, T>, fn: (key: string, value: T) => string): Record<string, T>;
export function filterValues<T>(obj: Record<string, T>, fn: (value: T, key: string) => boolean): Partial<Record<string, T>>;
export function filterKeys<T>(obj: Record<string, T>, fn: (key: string) => boolean): Partial<Record<string, T>>;
export function reduceObject<T, U>(obj: Record<string, T>, fn: (acc: U, value: T, key: string) => U, init: U): U;
export function forOwn<T>(obj: Record<string, T>, fn: (value: T, key: string) => void): void;
export function invert(obj: Record<string, string>): Record<string, string>;
export function renameKey(obj: object, oldKey: string, newKey: string): object;
export function renameKeys(obj: object, keyMap: Record<string, string>): object;
export function swapKeysValues(obj: Record<string, string>): Record<string, string>;
export function sortByKey(obj: Record<string, any>): Record<string, any>;
export function sortByValue(obj: Record<string, any>): [string, any][];
export function findKey(obj: Record<string, any>, fn: (value: any, key: string) => boolean): string | undefined;
export function findValue(obj: Record<string, any>, fn: (value: any, key: string) => boolean): any;
export function flattenObject(obj: Record<string, any>, prefix?: string): Record<string, any>;
export function unflattenObject(obj: Record<string, any>): Record<string, any>;
export function toQueryString(obj: Record<string, any>): string;
export function fromQueryString(qs: string): Record<string, string>;
export function diffObjects(obj1: Record<string, any>, obj2: Record<string, any>): Record<string, { from: any; to: any }>;
export function paths(obj: Record<string, any>): string[];
export function groupByKey<T>(arr: T[], key: keyof T): Record<string, T[]>;
export function countByKey<T>(arr: T[], key: keyof T): Record<string, number>;
export function freezeDeep<T extends object>(obj: T): Readonly<T>;
export function strict<T extends object>(obj: T): T;
export function compactObject<T extends object>(obj: T): Partial<T>;

// ─── DATE UTILITIES ───────────────────────────────────────────────────────────
export function now(): Date;
export function today(): Date;
export function yesterday(): Date;
export function tomorrow(): Date;
export function utcNow(): Date;
export function parseDate(val: string | number | Date): Date;
export function formatDate(date: Date | string | number, formatStr?: string): string;
export function formatDateISO(date: Date | string | number): string;
export function formatDateLocale(date: Date | string | number, locale?: string, options?: Intl.DateTimeFormatOptions): string;
export function formatTime(date: Date | string | number): string;
export function formatDateTime(date: Date | string | number): string;
export function formatRelative(date: Date | string | number): string;
export function formatDuration(ms: number): string;
export function timeAgo(date: Date | string | number): string;
export function addMilliseconds(date: Date | string | number, n: number): Date;
export function addSeconds(date: Date | string | number, n: number): Date;
export function addMinutes(date: Date | string | number, n: number): Date;
export function addHours(date: Date | string | number, n: number): Date;
export function addDays(date: Date | string | number, n: number): Date;
export function addWeeks(date: Date | string | number, n: number): Date;
export function addMonths(date: Date | string | number, n: number): Date;
export function addYears(date: Date | string | number, n: number): Date;
export function subMilliseconds(date: Date | string | number, n: number): Date;
export function subSeconds(date: Date | string | number, n: number): Date;
export function subMinutes(date: Date | string | number, n: number): Date;
export function subHours(date: Date | string | number, n: number): Date;
export function subDays(date: Date | string | number, n: number): Date;
export function subWeeks(date: Date | string | number, n: number): Date;
export function subMonths(date: Date | string | number, n: number): Date;
export function subYears(date: Date | string | number, n: number): Date;
export function diffMs(a: Date | string | number, b: Date | string | number): number;
export function diffSeconds(a: Date | string | number, b: Date | string | number): number;
export function diffMinutes(a: Date | string | number, b: Date | string | number): number;
export function diffHours(a: Date | string | number, b: Date | string | number): number;
export function diffDays(a: Date | string | number, b: Date | string | number): number;
export function diffWeeks(a: Date | string | number, b: Date | string | number): number;
export function diffMonths(a: Date | string | number, b: Date | string | number): number;
export function diffYears(a: Date | string | number, b: Date | string | number): number;
export function startOfDay(date: Date | string | number): Date;
export function endOfDay(date: Date | string | number): Date;
export function startOfWeek(date: Date | string | number): Date;
export function endOfWeek(date: Date | string | number): Date;
export function startOfMonth(date: Date | string | number): Date;
export function endOfMonth(date: Date | string | number): Date;
export function startOfYear(date: Date | string | number): Date;
export function endOfYear(date: Date | string | number): Date;
export function startOfHour(date: Date | string | number): Date;
export function endOfHour(date: Date | string | number): Date;
export function startOfMinute(date: Date | string | number): Date;
export function endOfMinute(date: Date | string | number): Date;
export function isToday(date: Date | string | number): boolean;
export function isYesterday(date: Date | string | number): boolean;
export function isTomorrow(date: Date | string | number): boolean;
export function isWeekend(date: Date | string | number): boolean;
export function isWeekday(date: Date | string | number): boolean;
export function isLeapYear(dateOrYear: Date | number): boolean;
export function isBefore(a: Date | string | number, b: Date | string | number): boolean;
export function isAfter(a: Date | string | number, b: Date | string | number): boolean;
export function isBetween(date: Date | string | number, start: Date | string | number, end: Date | string | number): boolean;
export function isSameDay(a: Date | string | number, b: Date | string | number): boolean;
export function isSameMonth(a: Date | string | number, b: Date | string | number): boolean;
export function isSameYear(a: Date | string | number, b: Date | string | number): boolean;
export function getDayName(date: Date | string | number, locale?: string): string;
export function getMonthName(date: Date | string | number, locale?: string): string;
export function getWeekOfYear(date: Date | string | number): number;
export function getDayOfYear(date: Date | string | number): number;
export function getQuarter(date: Date | string | number): number;
export function getDaysInMonth(date: Date | string | number): number;
export function getDaysInYear(date: Date | string | number): number;
export function toUnixTimestamp(date: Date | string | number): number;
export function fromUnixTimestamp(ts: number): Date;
export function toMilliseconds(date: Date | string | number): number;
export function fromMilliseconds(ms: number): Date;
export function countdown(date: Date | string | number): { total: number; days: number; hours: number; minutes: number; seconds: number };
export function dateRange(start: Date | string | number, end: Date | string | number, step?: string): Date[];
export function minDate(...dates: (Date | string | number)[]): Date;
export function maxDate(...dates: (Date | string | number)[]): Date;

// ─── VALIDATION ───────────────────────────────────────────────────────────────
export function isEmail(val: string): boolean;
export function isURL(val: string): boolean;
export function isAnyURL(val: string): boolean;
export function isGitHubURL(val: string): boolean;
export function isYouTubeURL(val: string): boolean;
export function isTwitterURL(val: string): boolean;
export function isIPv4(val: string): boolean;
export function isIPv6(val: string): boolean;
export function isIP(val: string): boolean;
export function isMACAddress(val: string): boolean;
export function isPhone(val: string): boolean;
export function isIndianPhone(val: string): boolean;
export function isCreditCard(val: string): boolean;
export function isVisa(val: string): boolean;
export function isMastercard(val: string): boolean;
export function isAmex(val: string): boolean;
export function isUUID(val: string): boolean;
export function isUUIDv4(val: string): boolean;
export function isISBN(val: string): boolean;
export function isISBN10(val: string): boolean;
export function isISBN13(val: string): boolean;
export function isJWT(val: string): boolean;
export function isSemver(val: string): boolean;
export function isAlpha(val: string): boolean;
export function isAlphaNumeric(val: string): boolean;
export function isNumeric(val: string): boolean;
export function isHex(val: string): boolean;
export function isSlug(val: string): boolean;
export function isHexColor(val: string): boolean;
export function isRGB(val: string): boolean;
export function isRGBA(val: string): boolean;
export function isHSL(val: string): boolean;
export function isLatitude(val: string | number): boolean;
export function isLongitude(val: string | number): boolean;
export function isLatLng(lat: string | number, lng: string | number): boolean;
export function isZipCode(val: string): boolean;
export function isIndianPincode(val: string): boolean;
export function isJSON(val: string): boolean;
export function isBase64(val: string): boolean;
export function isDataURI(val: string): boolean;
export function isMIMEType(val: string): boolean;
export function isMD5(val: string): boolean;
export function isSHA1(val: string): boolean;
export function isSHA256(val: string): boolean;
export function isSHA512(val: string): boolean;
export function isStrongPassword(val: string, options?: { minLength?: number; requireUppercase?: boolean; requireLowercase?: boolean; requireNumber?: boolean; requireSpecial?: boolean }): boolean;
export function passwordStrength(val: string): 0 | 1 | 2 | 3 | 4;
export function isUsername(val: string): boolean;
export function isPAN(val: string): boolean;
export function isAadhaar(val: string): boolean;
export function isGSTIN(val: string): boolean;
export function isIFSC(val: string): boolean;
export function isIBAN(val: string): boolean;
export function isBIC(val: string): boolean;
export function isCronExpression(val: string): boolean;
export function isVIN(val: string): boolean;
export function isEAN13(val: string): boolean;

// ─── FUNCTION UTILITIES ───────────────────────────────────────────────────────
export function debounce<T extends (...args: any[]) => any>(fn: T, wait?: number): T & { cancel(): void };
export function throttle<T extends (...args: any[]) => any>(fn: T, wait?: number): T;
export function once<T extends (...args: any[]) => any>(fn: T): T;
export function memoize<T extends (...args: any[]) => any>(fn: T, keyResolver?: (...args: any[]) => string): T;
export function compose<T>(...fns: Function[]): (x: T) => any;
export function pipe<T>(...fns: Function[]): (x: T) => any;
export function curry(fn: Function): Function;
export function partial(fn: Function, ...preArgs: any[]): Function;
export function flip<T extends (...args: any[]) => any>(fn: T): (...args: any[]) => ReturnType<T>;
export function negate<T extends (...args: any[]) => boolean>(predicate: T): T;
export function identity<T>(x: T): T;
export function constant<T>(value: T): () => T;
export function noop(): void;
export function delay(fn: Function, wait: number, ...args: any[]): Promise<any>;
export function defer(fn: Function, ...args: any[]): Promise<any>;
export function tryCatch(fn: Function, ...args: any[]): [Error, null] | [null, any];
export function tryCatchAsync(fn: Function, ...args: any[]): Promise<[Error, null] | [null, any]>;
export function promisify(fn: Function): (...args: any[]) => Promise<any>;
export function timed(fn: Function, label?: string): Function;
export function tap(fn: Function): (value: any) => any;
export function ary(fn: Function, n: number): Function;
export function unary(fn: Function): Function;
export function binary(fn: Function): Function;
export function times<T>(n: number, fn: (i: number) => T): T[];
export function memoizeAsync<T extends (...args: any[]) => Promise<any>>(fn: T, keyResolver?: Function): T;
export function trace(fn: Function, label?: string): Function;
export function sleep(ms: number): Promise<void>;

// ─── COLOR UTILITIES ──────────────────────────────────────────────────────────
export interface RGB { r: number; g: number; b: number }
export interface HSL { h: number; s: number; l: number }
export interface HSV { h: number; s: number; v: number }
export interface RGBA { r: number; g: number; b: number; a: number }

export function hexToRgb(hex: string): RGB;
export function rgbToHex(r: number, g: number, b: number): string;
export function hexToHsl(hex: string): HSL;
export function hslToHex(h: number, s: number, l: number): string;
export function hexToRgba(hex: string, alpha?: number): string;
export function rgbToHsl(r: number, g: number, b: number): HSL;
export function hslToRgb(h: number, s: number, l: number): RGB;
export function rgbToHsv(r: number, g: number, b: number): HSV;
export function darken(hex: string, amount?: number): string;
export function lighten(hex: string, amount?: number): string;
export function saturate(hex: string, amount?: number): string;
export function desaturate(hex: string, amount?: number): string;
export function grayscale(hex: string): string;
export function invertColor(hex: string): string;
export function mixColors(hex1: string, hex2: string, weight?: number): string;
export function complementary(hex: string): string;
export function analogous(hex: string, angle?: number): [string, string, string];
export function triadic(hex: string): [string, string, string];
export function tetradic(hex: string): [string, string, string, string];
export function splitComplementary(hex: string, angle?: number): [string, string, string];
export function getLuminance(r: number, g: number, b: number): number;
export function getContrastRatio(hex1: string, hex2: string): number;
export function isLightColor(hex: string): boolean;
export function isDarkColor(hex: string): boolean;
export function bestTextColor(bgHex: string): '#000000' | '#FFFFFF';
export function randomColor(): string;
export function randomPastel(): string;
export function colorPalette(n: number, s?: number, l?: number): string[];
export function parseColor(str: string): RGBA;
export function toHexColor(str: string): string;

// ─── ASYNC UTILITIES ──────────────────────────────────────────────────────────
export function retry(fn: () => Promise<any>, maxAttempts?: number, delayMs?: number): Promise<any>;
export function withTimeout(fn: (() => Promise<any>) | Promise<any>, ms: number): Promise<any>;
export function parallel(tasks: ((() => Promise<any>) | Promise<any>)[]): Promise<any[]>;
export function sequential(tasks: ((() => Promise<any>) | Promise<any>)[]): Promise<any[]>;
export function waterfall(fns: Function[], initial?: any): Promise<any>;
export function mapWithConcurrency<T, U>(items: T[], fn: (item: T, i: number) => Promise<U>, concurrency?: number): Promise<U[]>;
export function allSettled(promises: Promise<any>[]): Promise<PromiseSettledResult<any>[]>;
export function any(promises: Promise<any>[]): Promise<any>;
export function race(promises: Promise<any>[]): Promise<any>;
export function asyncMap<T, U>(arr: T[], fn: (item: T, i: number) => Promise<U>, concurrency?: number): Promise<U[]>;
export function asyncFilter<T>(arr: T[], predicate: (item: T) => Promise<boolean>): Promise<T[]>;
export function asyncReduce<T, U>(arr: T[], fn: (acc: U, item: T) => Promise<U>, init: U): Promise<U>;
export function asyncForEach<T>(arr: T[], fn: (item: T) => Promise<void>): Promise<void>;
export function whilst(predicate: () => Promise<boolean>, fn: () => Promise<void>): Promise<void>;
export function until(predicate: () => Promise<boolean>, fn: () => Promise<void>): Promise<void>;
export function timesAsync<T>(n: number, fn: (i: number) => Promise<T>): Promise<T[]>;
export function deferred<T>(): { promise: Promise<T>; resolve: (value: T) => void; reject: (reason?: any) => void };
export function createQueue(concurrency?: number): { add(task: () => Promise<any>): Promise<any>; readonly size: number; readonly running: number };
export function cancellable<T>(promiseFn: () => Promise<T>): { promise: Promise<T>; cancel(): void };
export function settle(promises: Promise<any>[]): Promise<PromiseSettledResult<any>[]>;
export function timed(fn: () => Promise<any>): Promise<{ result: any; duration: number }>;

// ─── DOM UTILITIES ────────────────────────────────────────────────────────────
export const isBrowser: boolean;
export function getElement(selector: string): Element | null;
export function getElements(selector: string): Element[];
export function getElementById(id: string): HTMLElement | null;
export function createElement(tag: string, attrs?: Record<string, any>, ...children: (string | Element)[]): HTMLElement | null;
export function removeElement(el: Element): void;
export function replaceElement(oldEl: Element, newEl: Element): void;
export function addClass(el: Element, ...classes: string[]): void;
export function removeClass(el: Element, ...classes: string[]): void;
export function toggleClass(el: Element, className: string, force?: boolean): void;
export function hasClass(el: Element, className: string): boolean;
export function setAttr(el: Element, key: string, value: string): void;
export function getAttr(el: Element, key: string): string | null;
export function removeAttr(el: Element, key: string): void;
export function hasAttr(el: Element, key: string): boolean;
export function setCss(el: HTMLElement, prop: string, value: string): void;
export function getCss(el: HTMLElement, prop: string): string | null;
export function setCssMany(el: HTMLElement, styles: Partial<CSSStyleDeclaration>): void;
export function on(el: EventTarget, event: string, handler: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): () => void;
export function off(el: EventTarget, event: string, handler: EventListenerOrEventListenerObject): void;
export function trigger(el: EventTarget, eventName: string, detail?: any): void;
export function once(el: EventTarget, event: string, handler: EventListenerOrEventListenerObject): void;
export function scrollToElement(el: Element, behavior?: ScrollBehavior): void;
export function scrollToTop(behavior?: ScrollBehavior): void;
export function getScrollPosition(): { x: number; y: number };
export function isInViewport(el: Element): boolean;
export function copyToClipboard(text: string): Promise<void>;
export function downloadFile(content: string | Blob, filename: string, type?: string): void;
export function getQueryParams(): Record<string, string>;
export function getQueryParam(name: string): string | null;
export function getCookie(name: string): string | null;
export function setCookie(name: string, value: string, days?: number, path?: string): void;
export function removeCookie(name: string, path?: string): void;
export function lsGet(key: string): any;
export function lsSet(key: string, value: any): void;
export function lsRemove(key: string): void;
export function lsClear(): void;
export function getTitle(): string;
export function setTitle(title: string): void;
export function isMobile(): boolean;
export function getViewport(): { width: number; height: number };
export function isPageHidden(): boolean;

// ─── NAMESPACED MODULE EXPORTS ────────────────────────────────────────────────
export declare namespace type { }
export declare namespace array { }
export declare namespace string { }
export declare namespace number { }
export declare namespace object { }
export declare namespace date { }
export declare namespace validation { }
export declare namespace color { }
export declare namespace async { }
export declare namespace dom { }

export declare const function: typeof import('./src/function');
